[package]
name = "wasm_keyboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uievents-code = { version = "0.1.2", features = ["enum"] }